server.port=8080

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/concept_clarity}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:SANJAY@4VZ24MC099}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:false}
spring.jpa.open-in-view=false

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
